<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="olive" ignored="0" name="TestNG tests" tests="14" failures="11" timestamp="05 Nov 2023 09:22:21 GMT" time="0.556" errors="0">
  <testcase name="testAdd_Announcement" time="0.273" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t add announcement expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't add announcement expected [true] but found [false]
at Model.ManegerNGTest.testAdd_Announcement(ManegerNGTest.java:249)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_Announcement -->
  <testcase name="testAdd_Castomer" time="0.148" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t add customer expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't add customer expected [true] but found [false]
at Model.ManegerNGTest.testAdd_Castomer(ManegerNGTest.java:225)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testAdd_Castomer -->
  <testcase name="testAdd_Restaurant" time="0.038" classname="Model.ManegerNGTest"/>
  <testcase name="testCheckUsr" time="0.012" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="found user expected [null] but found [Model.Castomer@1d76aeea]">
      <![CDATA[java.lang.AssertionError: found user expected [null] but found [Model.Castomer@1d76aeea]
at Model.ManegerNGTest.testCheckUsr(ManegerNGTest.java:108)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testCheckUsr -->
  <testcase name="testDelete_Announcement" time="0.003" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t preform the test because isExists don&amp;apos;t work or the test restaurant dosn&amp;apos;t exists expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't preform the test because isExists don't work or the test restaurant dosn't exists expected [true] but found [false]
at Model.ManegerNGTest.testDelete_Announcement(ManegerNGTest.java:198)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testDelete_Announcement -->
  <testcase name="testDelete_Castomer" time="0.005" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t preform the test because isExists don&amp;apos;t work or the test customer dosn&amp;apos;t exists expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't preform the test because isExists don't work or the test customer dosn't exists expected [true] but found [false]
at Model.ManegerNGTest.testDelete_Castomer(ManegerNGTest.java:173)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testDelete_Castomer -->
  <testcase name="testDelete_Restaurant" time="0.02" classname="Model.ManegerNGTest"/>
  <testcase name="testFind" time="0.007" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t find restaurant expected [Model.Restaurant@f8c1ddd] but found [null]">
      <![CDATA[java.lang.AssertionError: couldn't find restaurant expected [Model.Restaurant@f8c1ddd] but found [null]
at Model.ManegerNGTest.testFind(ManegerNGTest.java:115)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- testFind -->
  <testcase name="testGetInstance" time="0.0" classname="Model.ManegerNGTest"/>
  <testcase name="testIsExists_Announcement" time="0.003" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t find announcement expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't find announcement expected [true] but found [false]
at Model.ManegerNGTest.testIsExists_Announcement(ManegerNGTest.java:149)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testIsExists_Announcement -->
  <testcase name="testIsExists_Castomer" time="0.006" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t find castomer expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't find castomer expected [true] but found [false]
at Model.ManegerNGTest.testIsExists_Castomer(ManegerNGTest.java:127)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testIsExists_Castomer -->
  <testcase name="testIsExists_Restaurant" time="0.004" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t find restaurant expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: couldn't find restaurant expected [true] but found [false]
at Model.ManegerNGTest.testIsExists_Restaurant(ManegerNGTest.java:138)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- testIsExists_Restaurant -->
  <testcase name="testSearch" time="0.007" classname="Model.ManegerNGTest">
    <failure type="java.lang.AssertionError" message="couldn&amp;apos;t find restaurant by name">
      <![CDATA[java.lang.AssertionError: couldn't find restaurant by name
at Model.ManegerNGTest.testSearch(ManegerNGTest.java:161)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- testSearch -->
  <testcase name="testUpdate_Restaurant_Restaurant" time="0.003" classname="Model.ManegerNGTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at Model.ManegerNGTest.testUpdate_Restaurant_Restaurant(ManegerNGTest.java:257)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- testUpdate_Restaurant_Restaurant -->
</testsuite> <!-- TestNG tests -->
